import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import { ThemeProvider } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import './index.css'
import App from './App.tsx'

// amplify_outputs.json is generated by `npx ampx sandbox` and is gitignored,
// so it may be absent. import.meta.glob resolves to {} when the file does not
// exist (no build error) and to the module when it does — configuring Amplify
// automatically once a sandbox has been deployed.
const outputsModules = import.meta.glob('../amplify_outputs.json', {
  eager: true,
}) as Record<string, { default: Record<string, unknown> }>

const outputs = Object.values(outputsModules)[0]?.default
if (outputs) {
  Amplify.configure(outputs)
} else {
  console.warn(
    'amplify_outputs.json not found — run `npx ampx sandbox` to generate it. ' +
      'The app runs against the stub handler until then.',
  )
}

// colorMode="system" makes every Amplify component follow the OS light/dark
// setting consistently, so fields, labels, and buttons all match the page.
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ThemeProvider colorMode="system">
      <App />
    </ThemeProvider>
  </StrictMode>,
)
